# Generated by Django 3.0.2 on 2020-07-21 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0008_auto_20200712_1826'),
        ('account', '0004_auto_20200713_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='moh7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='daira.Mol7aka'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150, null=True),
        ),
    ]
