# Generated by Django 3.0.2 on 2020-02-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
