# Generated by Django 3.0.2 on 2020-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200203_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_keywords',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
