# Generated by Django 3.0.2 on 2020-02-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200204_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'link'), (2, 'page'), (3, 'catagory')])),
                ('visibility', models.IntegerField(choices=[(1, 'all'), (2, 'only guest'), (3, 'only logged in'), (4, 'only logged in admin')])),
                ('css_class', models.CharField(blank=True, max_length=128, null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Menu')),
            ],
        ),
    ]
