# Generated by Django 3.0.2 on 2020-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_menu_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='path',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'link'), (2, 'page'), (3, 'collection')], default=1),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'all'), (2, 'only guest'), (3, 'only logged in'), (4, 'only logged in admin')], default=1),
        ),
    ]
