# Generated by Django 3.0.2 on 2020-06-01 19:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200211_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
