"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0(#42x64gp8mrpxq@$39r)jr@)55ovfe2dl%4kmp*f48&j*k+f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'account',
    'mysite.apps.MyAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',

    'api',
    'daira',
    'sokna',
    'pages',
    'settings',
    'extra_settings',

    'adminsortable2',
    'ckeditor',
    'crispy_forms',
    'cuser',
    'crequest',
    # for file manager (django-filer)
    # 'easy_thumbnails',
    # 'filer',
    # 'mptt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'mysite.middleware.LocaleAdminMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # added middlewares
    'cuser.middleware.CuserMiddleware',
    'crequest.middleware.CrequestMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Set a custum User admin.
AUTH_USER_MODEL = 'account.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
  ('en', _('English')),
  ('ar', _('Arabic')),
  # ('fr', _('French'))
]

TIME_ZONE = 'Africa/Casablanca' # default: UTC

USE_I18N = True

USE_L10N = False

USE_TZ = True

# datetime format
DATETIME_FORMAT = 'd/m/Y H:i:s'
DATE_FORMAT = 'd/m/Y'

# translated files
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mysite/static')
]

# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.SUCCESS: 'success',
    messages.INFO: 'info',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
    messages.DEBUG: 'secondary'
}

# login page
LOGIN_URL = 'account:login'

# crispy forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_FAIL_SILENTLY = not DEBUG

# Emailling Server.
EMAIL_HOST          = os.getenv('EMAIL_HOST')
EMAIL_PORT          = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER     = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASS')
EMAIL_USE_SSL       = True
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER # this should be no-replay@domain.com

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# CKEditor
# CKEDITOR_UPLOAD_PATH = 'ckeditor/uploads/'
# CKEDITOR_UPLOAD_SLUGIFY_FILENAME = True
# CKEDITOR_RESTRICT_BY_USER = True
# CKEDITOR_BROWSE_SHOW_DIRS = True
# CKEDITOR_RESTRICT_BY_DATE = True
# CKEDITOR_IMAGE_BACKEND = 'pillow'
# CKEDITOR_FORCE_JPEG_COMPRESSION = True
# CKEDITOR_IMAGE_QUALITY = 95

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'width': 900,
        'toolbar_Custom': [
                ["Format", "Bold", "Italic", "Underline", "Strike", "SpellChecker"],
                ['NumberedList', 'BulletedList', "Indent", "Outdent", 'JustifyLeft', 'JustifyCenter',
                 'JustifyRight', 'JustifyBlock'],
                ["Image", "Table", "Link", "Unlink", "Anchor", "SectionLink", "Subscript", "Superscript", "HorizontalRule"],
                ['Smiley'],
                ['Undo', 'Redo'],
                ["Source"],
                ["Maximize"]
        ]
    }
}

######################### REST_FRAMEWORK #########################
# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ]
# }

######################## Cookie settings #########################
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_SECURE = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

####################### My custom settings #######################
APP_NAME = 'idarati'
APP_VERSION = '0.2.0'
POWRED_BY = 'Mohammed Ramouchy'
POWRED_BY_URL = 'https://github.com/medram'
POWRED_BY_EMAIL = 'mohammed@ramouchy.com'
