# Generated by Django 3.0.2 on 2020-06-03 14:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('CIN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('born', models.DateField(blank=True, null=True)),
                ('handicapped', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'individuals',
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'streets',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='daira.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_1', to='daira.Individual')),
                ('individual_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_2', to='daira.Individual')),
                ('relationship_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='daira.RelationshipType')),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='relation',
            field=models.ManyToManyField(related_name='_individual_relation_+', through='daira.Relationship', to='daira.Individual'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('zip_code', models.CharField(blank=True, max_length=16, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daira.City')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daira.Individual')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='daira.Street')),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'db_table': 'addresses',
            },
        ),
    ]
