# Generated by Django 3.0.2 on 2020-06-03 14:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
