# Generated by Django 3.0.2 on 2020-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0003_auto_20200603_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.AddField(
            model_name='individual',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='jobs',
            field=models.ManyToManyField(related_name='individuals', to='daira.Job'),
        ),
    ]
