# Generated by Django 3.0.2 on 2020-06-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0004_auto_20200604_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Mol7aka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('amala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daira.Amala')),
            ],
        ),
    ]
