# Generated by Django 3.0.2 on 2020-06-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0005_amala_mol7aka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amala',
            options={'verbose_name_plural': 'Amalat'},
        ),
        migrations.AlterModelOptions(
            name='mol7aka',
            options={'verbose_name_plural': 'Mol7akat'},
        ),
        migrations.AlterField(
            model_name='mol7aka',
            name='amala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mol7akat', to='daira.Amala'),
        ),
    ]
