# Generated by Django 3.0.2 on 2020-07-12 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0006_auto_20200604_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amala',
            options={'verbose_name': 'Amala', 'verbose_name_plural': 'Amalat'},
        ),
        migrations.AlterModelOptions(
            name='mol7aka',
            options={'verbose_name': 'Administrative attache', 'verbose_name_plural': 'Administrative attaches'},
        ),
        migrations.AddField(
            model_name='amala',
            name='name_in_arabic',
            field=models.CharField(default='مرحبا', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mol7aka',
            name='name_in_arabic',
            field=models.CharField(default=datetime.datetime(2020, 7, 12, 12, 29, 52, 188657, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
