# Generated by Django 3.0.2 on 2020-07-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0007_auto_20200712_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='daira.Mol7aka'),
        ),
        migrations.AddField(
            model_name='individual',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='daira.Mol7aka'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='daira.Mol7aka'),
        ),
        migrations.AddField(
            model_name='report',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='daira.Mol7aka'),
        ),
        migrations.AddField(
            model_name='street',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='daira.Mol7aka'),
        ),
    ]
