# Generated by Django 3.0.2 on 2020-08-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0008_auto_20200712_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='born',
        ),
        migrations.AddField(
            model_name='individual',
            name='ar_firstname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='ar_lastname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='born_d',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day of birth'),
        ),
        migrations.AddField(
            model_name='individual',
            name='born_m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Month of birth'),
        ),
        migrations.AddField(
            model_name='individual',
            name='born_no_d_m',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="I don't have day & month of my birthday"),
        ),
        migrations.AddField(
            model_name='individual',
            name='born_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of birth'),
        ),
        migrations.AddField(
            model_name='individual',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='individuals/cin_photos', verbose_name='Front face of CIN'),
        ),
        migrations.AddField(
            model_name='individual',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='individuals/cin_photos', verbose_name='Back face of CIN'),
        ),
        migrations.AlterField(
            model_name='address',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='daira.Mol7aka', verbose_name='Administrative attache'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='daira.Mol7aka', verbose_name='Administrative attache'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='daira.Mol7aka', verbose_name='Administrative attache'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='daira.Mol7aka', verbose_name='Administrative attache'),
        ),
        migrations.AlterField(
            model_name='street',
            name='mol7aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='daira.Mol7aka', verbose_name='Administrative attache'),
        ),
    ]
