# Generated by Django 3.0.2 on 2020-08-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0010_auto_20200816_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='income_level',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Very high'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Very Low')], default=0, verbose_name='Income level'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='social_status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Single'), (2, 'Married'), (3, 'Divorced')], default=0, verbose_name='Social status'),
        ),
    ]
