# Generated by Django 3.0.2 on 2020-06-04 14:20

import daira.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daira', '0006_auto_20200604_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoknaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('born', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('photo_1', models.ImageField(upload_to='cin_photos')),
                ('photo_2', models.ImageField(upload_to='cin_photos')),
                ('phone', models.IntegerField(validators=[daira.validators.PhoneValidator])),
                ('address', models.CharField(max_length=256)),
                ('mol7aka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='daira.Mol7aka')),
            ],
            options={
                'db_table': 'sokna_requests',
            },
        ),
    ]
