# Generated by Django 3.0.2 on 2020-06-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soknarequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
