# Generated by Django 3.0.2 on 2020-06-05 12:17

import daira.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soknarequest',
            name='born',
        ),
        migrations.AddField(
            model_name='soknarequest',
            name='born_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soknarequest',
            name='born_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soknarequest',
            name='born_no_d_m',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="I don't have day & month of my birthday"),
        ),
        migrations.AddField(
            model_name='soknarequest',
            name='born_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soknarequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='soknarequest',
            name='terms_of_use',
            field=models.BooleanField(default=False, validators=[daira.validators.TermsOfUse], verbose_name='I confess that all the above information are correct.'),
        ),
    ]
