# Generated by Django 3.0.2 on 2020-06-06 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sokna', '0003_auto_20200605_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='soknarequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soknarequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
