# Generated by Django 3.0.2 on 2020-07-12 12:29

import daira.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daira', '0007_auto_20200712_1329'),
        ('sokna', '0005_soknarequest_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soknarequest',
            options={'verbose_name': 'Residential statement order', 'verbose_name_plural': 'Residential statement orders'},
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='CIN',
            field=models.CharField(max_length=10, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Current residence Address'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='born_d',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day of birth'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='born_m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Month of birth'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='born_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of birth'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='firstname',
            field=models.CharField(max_length=32, verbose_name='Fistname'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='lastname',
            field=models.CharField(max_length=32, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='mol7aka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='daira.Mol7aka', verbose_name='Administrative attache'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='phone',
            field=models.BigIntegerField(validators=[daira.validators.PhoneValidator], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='photo_1',
            field=models.ImageField(upload_to='cin_photos', verbose_name='Front face of CIN'),
        ),
        migrations.AlterField(
            model_name='soknarequest',
            name='photo_2',
            field=models.ImageField(upload_to='cin_photos', verbose_name='Back face of CIN'),
        ),
    ]
